### ISSUE TITLE
The system does not automatically recover from failures

### ISSUE THREAD

**Issue by thewillyhuman** [weso/rdfshape-api#109]
When there's an error in the server the system does not have the abillity to automatically recover from that error, for example kill the process and launch it again.

The easiest way to notice is that the fields on the forms appear empty since the front does not connect to the back, which is down.

This is interesting as the system goes down more often than we'd like.

**Comment by ulitol97** [comment]
This is interesting, even more now that we have a critical issue open (#196).

I was thinking about using the [Monit](https://mmonit.com/monit/) utility (repo [here](https://bitbucket.org/tildeslash/monit/src/master/)). Looks like it can perform scripted actions if certain ports do not respond or the PID from a pidfile is not present.

Most tools I've seen are oriented towards monitoring services rather than processes like RdfShape... Any other idea before I try anything out? @thewilly @labra

**Comment by thewilly** [comment]
Very similar to you idea, a shell script that checks if the PID of the process is running, else start the system again. I know that they use this same method for every micro-service at PCCOMPONENTES and that there is a video explaining it. If you need the reference I will look for it. But, as said, very similar to your proposal.

**Comment by ulitol97** [comment]
Sounds fine and simple, can you find the reference (just for curiosity's sake 🤔)?

**Comment by ulitol97** [comment]
This issue has been fixed by implementing healthcheks to the deployed containers in coordination with [docker-autoheal](https://github.com/willfarrell/docker-autoheal), which has proven simple and effective for now.
