### ISSUE TITLE
Create a docker image with rdfshape-client, wikishape and rdfshape server all together

### ISSUE THREAD

**Issue by labra** [weso/rdfshape-api#239]
Create a docker image that contains the following components:
- [rdfshape-client](https://github.com/weso/rdfshape-client) aka rdfshape 
- [wikishape](https://github.com/weso/wikishape)
- [rdfshape server](https://github.com/weso/rdfshape)
- Some monitorization system. It seems that http4s already has middleware for Promotheus metrics.

In the case of rdfshape, some time ago we already created a docker version using [sbt-native package](https://www.scala-sbt.org/sbt-native-packager/formats/docker.html)

**Comment by labra** [comment]
We may consider include [sheXer](https://github.com/weso/shexer) in the docker image.

**Comment by ulitol97** [comment]
We could dockerize all applications individually and then use docker-compose to launch them altogether. What do you think?

**Comment by labra** [comment]
Yes, that's also what I was thinking.

**Comment by ulitol97** [comment]
Both server and client are containerized now, you may see the Dockerfiles in the repositories and further explanations in their README files.

After some testing I consider the images to be good enough **for now**, so I uploaded both of them to Docker Hub with decent READMEs too✌🏼 ([api](https://hub.docker.com/r/wesogroup/rdfshape-api), [client](https://hub.docker.com/r/wesogroup/rdfshape-client)).

Next steps are:
- Easily deploying the full RDFShape stack with docker compose.
- Deploying RDFShape along with Nginx (reverse proxy and SSL management) in our deployment environment.
- Automatically recover or substitute containers on failure.

**Comment by ulitol97** [comment]
**Status update:**
I'm already deploying the full RDFShape stack locally with docker-compose without any problem. A third container using Nginx as a reverse proxy has proven to be the best way to handle connections (so that everything is accessible on port 80) and SSL certificates.

**Some questions I'd like help with:**
Regarding the automatic recovery of failing containers, it is possible to use the [healthcheck instruction](https://docs.docker.com/engine/reference/builder/#healthcheck) in a dockerfile for Docker to mark a container as "unhealthy". 
However, it seems Docker itself isn't capable of restarting unhealthy containers automatically and I'm struggling to find the best solution for this problem in our use case. Some alternatives I've found:
1. Having another container with an "always-restart" policy monitoring the rest of the stack ([willfarrell/docker-autoheal](https://github.com/willfarrell/docker-autoheal) looks like a popular solution).
2. Having the healthcheck itself kill the container's main process, effectively killing it; as seen [here](https://stackoverflow.com/a/64041910/9744696).
3. Using a container orchestration tool like [Kubernetes](https://kubernetes.io/) or Docker's [swarm mode](https://docs.docker.com/engine/swarm/). This looks like the least "hacky" way of doing things, but using these tools may be overkill for us.

Any ideas? @weso/rdfshape

**Comment by thewillyhuman** [comment]
Good! I think it's great that we already have it dockerized. I don't know if there is a CD pipeline that uploads the images to a repository right now. If not, it could be very interesting to explore this. Thus, every time something is modified in rdfshape, the corresponding image is automatically published.

Regarding the ephemeral containers (containers that can die and lift automatically), I think it's great! As I understand it, that is the philosophy of containers. Regarding how to do it, I have always used a container scheduler for it (swarm/k8). Your option 3. I don't know if the other two alternatives work. But, if you want to explore them, count on me!

**Comment by ulitol97** [comment]
Yes, I'm planning on spending some time on creating automated actions that build and upload our docker images from our repos to Docker Hub.

Regarding the ephemeral containers, I'll give it a second thought in the meantime. For now I think I'll do some testing with K8s and keep you all informed ^^.

**Comment by thewillyhuman** [comment]
Not sure if GitHub provides an images [registry](https://docs.github.com/es/packages/guides/about-github-container-registry). If it does, and if it fits our needs, we can centralize our artifacts and software development pipelines on GitHub. This is related to https://github.com/weso/shex-s/issues/185.

**Comment by ulitol97** [comment]
Sounds like a good idea and alternative to Docker Hub (taking for granted that GitHub Container Registry suits us). I reckon that GCR integrates well with GitHub actions. Any opinion @labra?

**Comment by ulitol97** [comment]
Update:
- Switched to GitHub Container Registry and introduced it in our workflow:
  - Started storing our Docker images in GitHub Container Registry.
  - Created an automated pipeline via GitHub actions in order to automatically build and publish Docker images of our services after pushes to master
  - Images can be found here:
    - [API](https://github.com/orgs/weso/packages/container/package/rdfshape-api)
    - [Client](https://github.com/orgs/weso/packages/container/package/rdfshape-client)
    - [Wikishape](https://github.com/orgs/weso/packages/container/package/wikishape)

- (Finally) deployed RDFShape using Docker Compose and updated the deployment guide in the [wiki](https://github.com/weso/wesolocal/wiki/rdfshape#manuales-de-despliegue).
