### ISSUE TITLE
Check url parameters for shape map

### ISSUE THREAD

**Issue by labra** [weso/rdfshape-api#306]
It seems that we broke compatibility with Eric's validator changing the url parameter for shape map according to [the following comment](https://discord.com/channels/933388652673916989/933388652673916992/967691127404785704) from discord:

> i notice that RDFShape has changed the shape-map URL parameter to shapeMap
> should i change my interface as to match?
> (basically, have you thought about this and concluded it's consistent with other stuff?)
> i'd like to publish EXTENDS, but that branch of the primer includes synthesized links to both of our interfaces
> i can update mine to grandfather the shape-map and make shapeMap the canonical parameter (once i know you've thought about this and not just landed there inadvertently)
> 

We should check if we can revert the change to keep it compatible with Eric's tool.

**Comment by labra** [comment]
I have just copy/pasted the comment from Discord...the main issue I think is that at some point we changed the URL parameter to identify shape maps from `shape-map` to `shapeMap` and that Eric has a tool that automatically generates invocations to the validation tool which have been broken by that change. 

In principle, I think we can revert the change without breaking any other tool to keep compatibility with Eric's interface.

**Comment by ulitol97** [comment]
I've been looking into it.

In summary: it is doable but it would be much easier for Eric to change his interface to adapt to ours, seeing that he already proposed to do so.

**Comment by labra** [comment]
If it doesn't break nothing in our side, I would prefer to change it in our system to avoid breaking further things like the ShEx primer which may contain links to rdfshape or shex-simple...

**Comment by ulitol97** [comment]
It'd generate very verbose code to check both parameter names (plus that it would surely arise confusions in the future), so having two possible parameter names is discarded IMO.

Given that, what is left is to choose whether to use `shape-map` or `shapeMap`. I argue for `shapeMap` because:
- The parameter name has been changed for months without anyone complaining, and is specified as `shapeMap` in the [API Docs](https://app.swaggerhub.com/apis-docs/weso/RDFShape/#/shapemap/postShapemapInfo-body), which should be the reference.
- Changing it now would break RDFShape Client and WikiShape, so there's always a client that is affected.
- We cannot expect to adapt to all clients, but the opposite. And for them it is a minor change whereas for us it'd break the camel-case style of query parameters.

**Comment by ulitol97** [comment]
The parameter name was eventually changed to `shape-map`.
