### ISSUE TITLE
HTML page responses in api instead of data

### ISSUE THREAD

**Issue by jathanasiou** [weso/rdfshape-api#74]
It appears that currently, when using the `http://rdfshape.weso.es/api/` server for API calls, HTML documents are being received as answer one or more endpoints. 

For Example:
`curl -X GET "http://rdfshape.weso.es/api/data/formats" -H  "accept: application/json"`
returns
```html
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="shortcut icon" href="/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="RDFShape client"/><link rel="manifest" href="/manifest.json"/><title>RDFShape</title><link href="/static/css/2.4f4d5dfe.chunk.css" rel="stylesheet"><link href="/static/css/main.3b104fc2.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(i){function e(e){for(var r,t,n=e[0],o=e[1],u=e[2],l=0,f=[];l<n.length;l++)t=n[l],Object.prototype.hasOwnProperty.call(p,t)&&p[t]&&f.push(p[t][0]),p[t]=0;for(r in o)Object.prototype.hasOwnProperty.call(o,r)&&(i[r]=o[r]);for(s&&s(e);f.length;)f.shift()();return c.push.apply(c,u||[]),a()}function a(){for(var e,r=0;r<c.length;r++){for(var t=c[r],n=!0,o=1;o<t.length;o++){var u=t[o];0!==p[u]&&(n=!1)}n&&(c.splice(r--,1),e=l(l.s=t[0]))}return e}var t={},p={1:0},c=[];function l(e){if(t[e])return t[e].exports;var r=t[e]={i:e,l:!1,exports:{}};return i[e].call(r.exports,r,r.exports,l),r.l=!0,r.exports}l.m=i,l.c=t,l.d=function(e,r,t){l.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},l.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},l.t=function(r,e){if(1&e&&(r=l(r)),8&e)return r;if(4&e&&"object"==typeof r&&r&&r.__esModule)return r;var t=Object.create(null);if(l.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:r}),2&e&&"string"!=typeof r)for(var n in r)l.d(t,n,function(e){return r[e]}.bind(null,n));return t},l.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return l.d(r,"a",r),r},l.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},l.p="/";var r=window["webpackJsonprdfshape-client"]=window["webpackJsonprdfshape-client"]||[],n=r.push.bind(r);r.push=e,r=r.slice();for(var o=0;o<r.length;o++)e(r[o]);var s=n;a()}([])</script><script src="/static/js/2.5a3941e3.chunk.js"></script><script src="/static/js/main.77a91491.chunk.js"></script></body></html>
```
while 
`curl -X GET "http://shaclex.herokuapp.com/api/data/formats" -H  "accept: application/json"`
returns a JSON array, as expected:
```json
["TURTLE","RDF/XML","JSON-LD","N-TRIPLES","RDF/JSON","TRIG","DOT"]
```

**Comment by labra** [comment]
Thanks for your comment. Your are right! 

We will try to repair it.

**Comment by labra** [comment]
What happens is that the server is working at another port: http://rdfshape.weso.es:8080

So, if you do: 

```
$ curl -X GET "http://rdfshape.weso.es:8080/api/data/formats" -H "accept: application/json"
["TURTLE","RDF/XML","JSON-LD","N-TRIPLES","RDF/JSON","TRIG","DOT"]
```
The reason is that the application that is being run at port 8080 is the real server (implemented in Scala with http4s), and the application that is being run at port 80 is a client app recently implemented in React.

We have several solutions:
- Wrap the Scala server API library with the React client
- Deploy the server to a more stable URI instead of 8080
- Deploy both the server and the React client in the same port. We had tried to follow this route but deploying the React client inside the http4s server didn't work (maybe because of using React Routes...)

**Comment by jathanasiou** [comment]
Thank you for clarifying that. In my opinion having the server run at 8080 is not really a problem so long as it is documented in the OpenAPI spec.

Instead of choice 2 
> Deploy the server to a more stable URI instead of 8080
I would suggest a different (sub)domain for the server, then having it run on default ports (80/443). The reason is because anything other than the protocol defaults would still require an explicit declaration in the specification file.

While all the alternatives sound good, they also sound somewhat work intensive (except perhaps the domain name change, though that depends on your  deployment setup).

Until one of these solutions is implemented, it would be quite beneficial to just declare that port. I will make a small Pull Request for that if you're interested

**Comment by labra** [comment]
Yes, by now, a simple solution was your pull request, thanks!

I will leave the issue open until we take a more elegant solution.

**Comment by ulitol97** [comment]
This problem was solved a few months ago by using a reverse proxy in our [deployment stack](https://github.com/weso/rdfshape).

Requests to the _api_ subdomain are directly routed to the backend API without the user needing to specify any port (the same goes for requests to clients).

Correct and complete API docs are automatically being generated as well (#292) and available [here](https://app.swaggerhub.com/apis-docs/weso/RDFShape).
